### PR TITLE
Adds a working GitHub CI workflow, reaches a sane/high coverage level

### PR DESCRIPTION
**Pull request by simonneutert**
## Purpose

have a code coverage in both lines and branches of 100 %

### Goals

- [x] add a working and passing multi-os, multi ruby version CI (matrix checks)
- [x] rake tasks updated - rubocop, tests and coverage work hand in hand together
- [x] remove travis ci (legacy)
- [x] check for a clean and lean gem package

### When merging this PR

**You should know**

- Coverage is pseudo 100 % as some logic would cost way more effort to spec, so `# :nocov:` was set in certain cases
- `sv-SE.yml` locales/fixtures are  to be named CASE SENSTIVE 😮‍💨 fml I nearly went mad ... reading through r18n and r18n-core gem gave me the clue 
- `JRuby` compatibility is tested now, too

- version bump to `0.6.0` 🚀 

## pre-PR coverage after setting up modern simplecov

```
Coverage report generated for RSpec to /home/runner/work/roda-i18n/roda-i18n/coverage.
Line Coverage: 98.44% (63 / 64)
Branch Coverage: 82.76% (24 / 29)
```

### Example of a branch "miss"

image

### CODE REVIEW

**Comment by simonneutert** [comment]
@kematzy I suggest releasing a gem from current `master` first: `v0.5.0`. 

Then merge this, when you are satisfied with the changes. 🤞  
And then release `v0.6.0` with these changes to RubyGems 🥳

**Comment by simonneutert** [comment]
@kematzy i will make ci pass again 🚀

**Comment by kematzy** [comment]
It seems that I screwed up the `sv-SE.yml` file while using the Github web editor to resolve a conflict.

**Comment by kematzy** [comment]
Sorted, all tests pass now

**Comment by simonneutert** [comment]
bug squashed 💪

**Comment by kematzy** [comment]
It seems your ``.tool_versions` file was recognized by my [Mise-en-place](https://mise.jdx.dev/lang/ruby.html) so it forced an update on my system.

What do you think, should this file be stored or ignored??  I would prefer ignored.

**Comment by simonneutert** [comment]
It is up for debate all the time in my head. I usually put it in.

I am absolutely fine with ignoring it.

**Comment by simonneutert** [comment]
It is up for debate all the time in my head, I usually tend to put it in. 

I am absolutely fine with your decision to ignore it.

**Comment by simonneutert** [comment]
Let's fix the status badge/icon for the current workflow status in the Readme with it.

I could jump in for both tasks, just let me know :v:

**Comment by kematzy** [comment]
Please feel free to proceed.

**Pull request merged**
